### PR TITLE
D1 emulation issues

### PR DESCRIPTION
**Pull request by btb**
Here's some little corrections for D1 emulation in d2x-rebirth. There is still a bunch of redundancy (two do_boss_stuff functions, etc) that could be merged, but I did this with as light a touch as possible and no noticeably wrong behavior.

### CODE REVIEW

**Comment by vLKp** [comment]
This breaks the `x86_64-pc-linux-gnu-g++-4.9.2` build and `mingw32-g++-4.8.3` build.  It probably applies to all optimized builds with working support for inlining and dead code elimination after constant folding.  I suspect your compiler fails the test(s) required to enable `DXX_PHYSFS_CHECK_WRITE_SIZE_OBJECT_SIZE`.  I think you need these tests to pass in order to enable it:
```
DXX-Archive.3: checking whether compiler optimizes function __attribute__((__error__))... yes
DXX-Archive.3: checking whether compiler optimizes __builtin_constant_p... yes
DXX-Archive.3: checking whether compiler optimizes __builtin_object_size... yes
```

For `x86_64-pc-linux-gnu-g++-4.9.2`, I get:
```
In file included from similar/main/ai.cpp:43:0:
In function 'typename std::enable_if<std::is_integral<_Tp>::value, long long int>::type PHYSFSX_check_write(PHYSFS_File*, const V*, PHYSFS_uint32, PHYSFS_uint32) [with V = signed char; typename std::enable_if<std::is_integral<_Tp>::value, long long int>::type = long long int; PHYSFS_File = PHYSFS_File; PHYSFS_uint32 = unsigned int]',
    inlined from 'int ai_save_state(PHYSFS_File*)' at similar/main/ai.cpp:4451:51:
common/include/physfsx.h:121:371: error: call to 'dxx_trap_overwrite' declared with attribute error: write size exceeds element size
  DXX_PHYSFS_CHECK_WRITE_SIZE_OBJECT_SIZE(S, C, v);
                                                                                                                                                                                                                                                                                                                                                                                   ^
In function 'typename std::enable_if<std::is_integral<_Tp>::value, long long int>::type PHYSFSX_check_write(PHYSFS_File*, const V*, PHYSFS_uint32, PHYSFS_uint32) [with V = signed char; typename std::enable_if<std::is_integral<_Tp>::value, long long int>::type = long long int; PHYSFS_File = PHYSFS_File; PHYSFS_uint32 = unsigned int]',
    inlined from 'int ai_save_state(PHYSFS_File*)' at similar/main/ai.cpp:4455:60:
common/include/physfsx.h:121:371: error: call to 'dxx_trap_overwrite' declared with attribute error: write size exceeds element size
  DXX_PHYSFS_CHECK_WRITE_SIZE_OBJECT_SIZE(S, C, v);
                                                                                                                                                                                                                                                                                                                                                                                   ^
In file included from similar/main/ai.cpp:43:0:
In function 'typename std::enable_if<std::is_integral<_Tp>::value, long long int>::type PHYSFSX_check_write(PHYSFS_File*, const V*, PHYSFS_uint32, PHYSFS_uint32) [with V = signed char; typename std::enable_if<std::is_integral<_Tp>::value, long long int>::type = long long int; PHYSFS_File = PHYSFS_File; PHYSFS_uint32 = unsigned int]',
    inlined from 'int ai_save_state(PHYSFS_File*)' at similar/main/ai.cpp:4451:51:
common/include/physfsx.h:121:371: error: call to 'dxx_trap_overwrite' declared with attribute error: write size exceeds element size
  DXX_PHYSFS_CHECK_WRITE_SIZE_OBJECT_SIZE(S, C, v);
                                                                                                                                                                                                                                                                                                                                                                                   ^
```

**Comment by vLKp** [comment]
Do you want me to merge a version that fixes the build break or do you want to rebuild the series with it fixed?

**Comment by vLKp** [comment]
Commit 33f0731d1143a571366ff639439783d237b85215 and commit 2b4aba341d5143bbd34e79f20ddcfa423cba6e07 look safe, build for me, and produce no obvious changes, so I pushed them into [unification/master](https://github.com/dxx-rebirth/dxx-rebirth/tree/unification/master).

**Comment by btb** [comment]
Thanks, yep those checks fail on OS X. Fix has been squashed into the commit.

**Comment by btb** [comment]
Are there other refinements to this you would like to see? merge together some of those redundant functions and globals?

**Comment by vLKp** [comment]
Code cleanup is always welcome, but right now this is stalled only for lack of time to review the changes.  I will try to get to it soon.

**Comment by zicodxx** [comment]
@vLKp I can take this over, too if you want.

**Comment by vLKp** [comment]
@zicodxx Thanks.  I decided to take this one since Github reported a merge conflict.  The conflict is in `similar/main/paging.cpp` and turned out to be trivial.  Bradley's change to a symbolic constant was too close to a range-for conversion, so it was flagged as a conflict.

**Pull request merged**
