### PR TITLE
Use custom fixed-point audio resampler

### PR DESCRIPTION
**Pull request by raptor**
- Hopefully fixes issues with poor quality resampling when using SDL_AudioCVT
- Converts 11025 Hz or 22050 Hz samples to the default 44100 Hz outputs
- Uses high order brick wall filter like Sound Blaster 16

I expect this needs some cleanup and I welcome any comments or criticism. I'm not quite sure what coding style to follow, so I welcome feedback on this, too.

Also, this code is 4x-8x faster than SDL_ConvertAudio for this game.

### CODE REVIEW

**Comment by vLKp** [comment]
That speed increase is impressive.  I will try to provide a detailed code review within the next few days.

**Comment by vLKp** [comment]
My apologies for the delay.  The Github inline code review interface has not been working well, and I was hoping that with a few days and a forced refresh, it would recover.  It hasn't.

https://github.com/dxx-rebirth/dxx-rebirth/blob/5165efbc46b9f31a4f36b935322387e86955894a/similar/arch/sdl/digi_mixer.cpp#L155

These tables are shared between the games, so they should be in a `namespace dcx` block.  Code or data which varies in Descent 1 versus Descent 2 should be in `namespace dsx`.

https://github.com/dxx-rebirth/dxx-rebirth/blob/5165efbc46b9f31a4f36b935322387e86955894a/similar/arch/sdl/digi_mixer.cpp#L174

This should be `constexpr`, since the table is never modified.  Also, where possible, I prefer `std::array<T, N> id` over `T id[N]`.

https://github.com/dxx-rebirth/dxx-rebirth/blob/5165efbc46b9f31a4f36b935322387e86955894a/similar/arch/sdl/digi_mixer.cpp#L183

Same comments.

https://github.com/dxx-rebirth/dxx-rebirth/blob/5165efbc46b9f31a4f36b935322387e86955894a/similar/arch/sdl/digi_mixer.cpp#L193

- Parameters should be `const` when possible.
- Length variables should be `std::size_t`.  In this case, `int32_t *coeffs, int coeffsLen` could be combined as `std::span<int32_t> coeffs`, and let the compiler deduce the extent.

https://github.com/dxx-rebirth/dxx-rebirth/blob/5165efbc46b9f31a4f36b935322387e86955894a/similar/arch/sdl/digi_mixer.cpp#L197

When the loop iteration variable (here, `nn`) is only updated by the loop control statement, I prefer using `xrange` to make this clearer:

```c++
for (const unsigned nn : xrange(signalLen))
```

Note that `xrange` requires an unsigned input.  `int` is signed; `std::size_t` is unsigned, so addressing one of the earlier requests will implicitly handle this requirement.

https://github.com/dxx-rebirth/dxx-rebirth/blob/5165efbc46b9f31a4f36b935322387e86955894a/similar/arch/sdl/digi_mixer.cpp#L199

Spelling error: `Determin` is missing an `e`.

https://github.com/dxx-rebirth/dxx-rebirth/blob/5165efbc46b9f31a4f36b935322387e86955894a/similar/arch/sdl/digi_mixer.cpp#L200-L201

Use an unsigned type for array indexing.

https://github.com/dxx-rebirth/dxx-rebirth/blob/5165efbc46b9f31a4f36b935322387e86955894a/similar/arch/sdl/digi_mixer.cpp#L205

I suggest:

```c++
for (const unsigned kk : xrange(min_idx, max_idx + 1))
```

Note that `xrange` follows the STL pattern that `end` is excluded, hence the need to add 1 here to match your use of `<=`.

https://github.com/dxx-rebirth/dxx-rebirth/blob/5165efbc46b9f31a4f36b935322387e86955894a/similar/arch/sdl/digi_mixer.cpp#L207

Prefer use of C++ `static_cast<>` instead of the functional style cast used here.

https://github.com/dxx-rebirth/dxx-rebirth/blob/5165efbc46b9f31a4f36b935322387e86955894a/similar/arch/sdl/digi_mixer.cpp#L224-L228

Where possible, use a syntax that allows the compiler to readily generate a bulk store operation.  For this purpose, it might be better, although slightly wasteful, to zero-fill the entire `output` buffer before beginning, and then not need to zero slices of it during iteration.

https://github.com/dxx-rebirth/dxx-rebirth/blob/5165efbc46b9f31a4f36b935322387e86955894a/similar/arch/sdl/digi_mixer.cpp#L259-L261

`coeffs` can be made `const auto`:

```c++
const auto &coeffs = upFactor ? coeffs_halfband : coeffs_quarterband;
```

https://github.com/dxx-rebirth/dxx-rebirth/blob/5165efbc46b9f31a4f36b935322387e86955894a/similar/arch/sdl/digi_mixer.cpp#L289

If a statement is not needed, delete it, rather than comment it out.

https://github.com/dxx-rebirth/dxx-rebirth/blob/5165efbc46b9f31a4f36b935322387e86955894a/similar/arch/sdl/digi_mixer.cpp#L305-L306

`unique_ptr` provides value by managing lifetime.  Defer the `.release()` until after `convert_audio` is done, so that the memory moves directly from a local `unique_ptr` into the `RAIIMix_Chunk`.

**Comment by raptor** [comment]
Hi, I have been quite busy but hope to get to this soon.

**Comment by vLKp** [comment]
I pulled this into my working copy and am working on the cleanups locally.  There is no need for you to work on this further.

**Pull request merged**
