### PR TITLE
RPi on unification

### PR DESCRIPTION
**Pull request by derhass**
With these changes, the RPi port builds again with current unification branch.

This is the updated version (replacing https://github.com/dxx-rebirth/dxx-rebirth/pull/47) with the correct git message for the merge :)

### CODE REVIEW

**Comment by zicodxx** [comment]
Thank you. I will take a quick look over them and merge afterwards. :)

**Comment by derhass** [comment]
Please note that building d1x and d2x works with these patches, but d2x doesn't seem to work. I'll have to invesitgate this further. However, those patches won't hurt in either case.

**Comment by zicodxx** [comment]
Does it only break the RPi build? in case if so, we can still patch this up later.

**Comment by derhass** [comment]
It doesn't break the build. Those patches don''t break anything (as far as I can tell), and normal desktop builds are totally unaffected.

The game just crashes on the Pi when trying to start a game after the main menu. It might be the case that it is just an out of memory conditon. I plan to debugg this. But building on the RPi with the new C++ code base takes several hours (instead of half an hour before), so things are moving slowly. I should set up some cross-compile environment.

**Comment by zicodxx** [comment]
Maybe it's also just a general regression. Yes, your changes don't look as if they break anything - let alone on the PC build. Merging. :)

**Pull request merged**
