### PR TITLE
Feat: Pitch unlocker

### PR DESCRIPTION
**Pull request by RedZakuII**
A friend of mine doesn't like to play with mouselook because it's "cheating". However, she also dislikes the halving of pitch speed as it discourages/punishes vertical movement. 

I made this patch to the engine so we could play the game together without the halving of pitch. It ended up feeling pretty nice in many respects, especially when dueling in maps that aren't merely flat planes. 

I figure maybe other people will also enjoy this. I haven't done a lot of C, so I hope the code is okay.

### CODE REVIEW

**Comment by vLKp** [comment]
On an initial read, the code looks fine.  Your editor seems to have reformatted many lines that you are not actually changing, though:

```
$ git diff --stat master refs/pull/657/head
 common/main/kconfig.h     |  2 ++
 common/main/multi.h       |  3 ++-
 common/main/playsave.h    |  1 +
 similar/main/kconfig.cpp  | 43 ++++++++++++++++++++++++++++++++-----------
 similar/main/menu.cpp     | 17 ++++++++++++++++-
 similar/main/net_udp.cpp  | 76 ++++++++++++++++++++++++++++++++++++++++------------------------------------
 similar/main/playsave.cpp | 10 ++++++++++
 7 files changed, 103 insertions(+), 49 deletions(-)

$ git diff --stat master refs/pull/657/head --ignore-space-change 
 common/main/kconfig.h     |  2 ++
 common/main/multi.h       |  3 ++-
 common/main/playsave.h    |  1 +
 similar/main/kconfig.cpp  | 27 ++++++++++++++++++++++++---
 similar/main/menu.cpp     | 15 +++++++++++++++
 similar/main/net_udp.cpp  |  4 ++++
 similar/main/playsave.cpp | 10 ++++++++++
 7 files changed, 58 insertions(+), 4 deletions(-)
```

Generally, I prefer that those two `diff --stat` runs yield very similar results.  In your case, it looks like 45 lines are just whitespace changes, with no functional change.  That makes the difference harder to review in the Github pull request web interface, and confuses `git blame` later, since it will default to attributing those changed lines to your pull, even though your change had no effect on the code.

Is your friend @narzepatel, the author of issue #650?  That issue requested this feature, but did not provide an implementation.

Barring some major discovery during a line-by-line review, I will likely merge this the next time I work on the code.

**Comment by RedZakuII** [comment]
It looks like there's a define that VS code reformatted a little bit - the backslashes got moved so they were aligned. Would you like me to force push a fix for that?

He's not someone I know, but I hope he enjoys the change!

**Comment by GoatMaiden** [comment]
It was me!

I was the one who also requested this specifically from @RedZakuII. 

I've been making a lot of levels lately, and the one thing on my mind is VERTICALITY. 

But I'm not seeing "Try banking and then turning left or right" as a feature. No, that's clearly a workaround. Even the pros have their pitch sensitivity turned up higher than turn, so we all know what we want.

The benefit of no-pitch-lock extends to joystick and keyboard users, unlike with "uncapped" turning, which only benefits mouse users. Furthermore, I've fought in many an epic air battle, regarding flightsims, and at least in WWI era planes, pitch was how you change direction fast, not turning. 

So there's really no precedent for it, and according to an original developer, Mike Kulas, "I think the main reason pitch & yaw had different speeds is we thought it was more difficult for people to manage choppy pitch over choppy yaw. We couldn't rely on the framerate being high enough, so we compensated that way."

So anyways, yeah. That's all I wanted to say. =D

I hope RedZakuII fixes those little issues you pointed out, and then I'll be supremely pleased to begin playing with friends and enemies using unhalved pitch.

**Comment by vLKp** [comment]
@RedZakuII wrote:

> Would you like me to force push a fix for that?

If you are comfortable using git tools to reverse that, go ahead.  Otherwise, I can amend the commit when I merge it.

> He's not someone I know, but I hope he enjoys the change!

Interesting.  Two independent requests (across three people) for the feature, all in relatively short order.

---

@GoatMaiden wrote:

> I've been making a lot of levels lately

I am pleased to see that.  I thought level creation had largely dropped off, so it is nice to hear that people are still making them.

> Even the pros have their pitch sensitivity turned up higher than turn, so we all know what we want.

Actually, I keep all mine the same, and all maxed out. ;)

> The benefit of no-pitch-lock extends to joystick and keyboard users, unlike with "uncapped" turning, which only benefits mouse users. 

I disagree here.  The cap is applied late in the kconfig processing, so all user input types should be affected by removing the cap.  However, I can certainly see that mouse users might find it easier than others to generate the inputs required to get the most benefit out of it.  I believe I found in testing that with the cap removed, I could stack keyboard input and joystick input in the same axis to go faster than either would do alone.

> So there's really no precedent for it, and according to an original developer

I have not seen that claim before.  Do you have a citation for it?  I would find it quite unfortunate that this cap, which multiple maintainers have preserved for the sake of tradition, was rooted in a workaround for input limitations, rather than concern about game balance.

> I hope RedZakuII fixes those little issues you pointed out

Even if he doesn't, I'm happy to fix them as part of the merge.  The current delay is because I wanted to fix issue #646 at the same time, and that is proving more time consuming than expected to isolate.

**Comment by RedZakuII** [comment]
I went ahead and fixed that big old block. Hopefully that'll make the commit look a little better.

**Comment by GoatMaiden** [comment]
Yeah, all I've got is this Discord screencap I saw in the r/Descent Discord channel. https://cdn.discordapp.com/attachments/426799704396005377/1006050617124474880/IMG_2847.png

I don't know if it was ever clarified in even more detail as to whether they'd like it "patched" if possible.

**Pull request merged**
