### PR TITLE
Interest check: Command line for the console?

### PR DESCRIPTION
**Pull request by btb**
One of the things I've done to d2x lately is make the ingame console essentially complete, including a command queue and the ability to easily add new cvars and commands to do pretty much anything you want.

cvars are used for all of the config, including pilot data, and joystick/mouse axis assignment. All game controls have corresponding console commands, which can be bound to keys or buttons with the "bind" command. You can make aliases for compound commands, execute scripts, etc.

These commits are all that is needed to get the basic thing running, including the following commands:
```
]help
Available commands:
    set
    wait
    help
    exec
    echo
    unalias
    alias
```

adding more commands is as simple as writing a function and then calling `	cmd_addcommand("mycmd", myfunc)`

Here's a list of the cvars and commands that are already working in d2x, just to give you an idea:
```
]set
con_threshold: 0
mouse_axisx: 4
mouse_invertx: 0
mouse_axisy: 2
mouse_inverty: 0
mouse_axisz: 0
mouse_invertz: 0
joy_advaxisx: 4
joy_invertx: 0
joy_advaxisy: 2
joy_inverty: 0
joy_advaxisz: 0
joy_invertz: 0
joy_advaxisr: 0
joy_invertr: 0
joy_advaxisu: 0
joy_invertu: 0
joy_advaxisv: 0
joy_invertv: 0
gamma: 0
r_aspectratio: 0
DigiVolume: 8
MidiVolume: 8
RedbookEnabled: 1
RedbookVolume: 8
StereoReverse: 0
GammaLevel: 0
DetailLevel: 4
in_joystick: 0
in_mouse: 0
joy_forwardsensitivity: 1.0
joy_pitchsensitivity: 1.0
joy_sidesensitivity: 1.0
joy_yawsensitivity: 1.0
joy_upsensitivity: 1.0
joy_banksensitivity: 1.0
joy_forwardthreshold: 0.16
joy_pitchthreshold: 0.08
joy_sidethreshold: 0.08
joy_yawthreshold: 0.08
joy_upthreshold: 0.08
joy_bankthreshold: 0.08
m_forward: 1.0
m_pitch: 1.0
m_side: 1.0
m_yaw: 1.0
m_up: 1.0
m_bank: 1.0
JoystickMin: 4,9,25,117835269
JoystickCen: 0,5,21,13
JoystickMax: 1606411168,32767,669203,1
LastPlayer: brad
LastMission: Descent: First Strike
VR_type: 0
VR_resolution: 0
VR_tracking: 0
MovieHires: 1
GuideBotName: GUIDE-BOT
PrimaryOrder: 9,8,7,6,5,4,3,2,1,0,255
SecondaryOrder: 9,8,4,3,1,5,0,255,7,6,2
CockpitViewLeft: 0
CockpitViewRight: 0
LifetimeKills: 0
LifetimeKilled: 0
LifetimeChecksum: 0
TauntMacro1: Why can't we all just get along?
TauntMacro2: Hey, I got a present for ya
TauntMacro3: I got a hankerin' for a spankerin'
TauntMacro4: This one's headed for Uranus
GameWidth: 800
GameHeight: 600
skill: 1
AutoLeveling: 1
crosshair: 1
CockpitMode: 3
vid_mode: 4
MissileView: 1
HeadlightActive: 1
GuidedBig: 0
AutomapHires: 0
AutomapGameres: 0
MenuGameres: 1
show_fps: 0
fov: 30
HighestLevel: 1
]help
Available commands:
    stoprecording
    recorddemo
    sizedown
    sizeup
    say
    map
    player
    weapon
    togglebomb
    headlight
    cycle2
    cycle
    bomb
    flare
    -afterburner
    +afterburner
    -automap
    +automap
    -attack2
    +attack2
    -attack
    +attack
    -rearview
    +rearview
    -nrgshield
    +nrgshield
    -cruiseoff
    +cruiseoff
    -cruisedown
    +cruisedown
    -cruiseup
    +cruiseup
    -back
    +back
    -forward
    +forward
    -bankright
    +bankright
    -bankleft
    +bankleft
    -bank
    +bank
    -movedown
    +movedown
    -moveup
    +moveup
    -moveright
    +moveright
    -moveleft
    +moveleft
    -strafe
    +strafe
    -right
    +right
    -left
    +left
    -lookup
    +lookup
    -lookdown
    +lookdown
    pixelaspect
    gl_texturemode
    tmap
    unbind
    bind
    set
    wait
    help
    exec
    echo
    unalias
    alias
```

Let me know what you think!

### CODE REVIEW

**Comment by vLKp** [comment]
I added an interactive console for different reasons back on my dev branch, and have been intending to forward port that to unification.  Your code could benefit from some C++ utilities, but I am open to the idea of serving both purposes through an interactive console.

**Comment by btb** [comment]
> vLKp commented an hour ago
> I added an interactive console for different reasons back on my dev branch, and have been intending to forward port that to unification. Your code could benefit from some C++ utilities, but I am open to the idea of serving both purposes through an interactive console.

I'm sure it could, c++ definitely shines brighter at text processing and queueing and such.

**Comment by btb** [comment]
is your dev branch online somewhere?

**Comment by vLKp** [comment]
Yes, as [branch master](https://github.com/dxx-rebirth/dxx-rebirth/tree/master).

**Comment by vLKp** [comment]
Sorry about all the in-issue comments.  Github "helpfully" cross-posts commit review comments into the attached pull request.

**Comment by btb** [comment]
I squashed together some of these follow-up commits, apologies if that messes with your local repo at all.

**Comment by btb** [comment]
phase 2? is working, over here: https://github.com/btb/dxx-rebirth/pull/2
It probably has some rough spots, but it seems to behave all right.

**Comment by vLKp** [comment]
@zicodxx: could you give an accept/reject decision on this pull?  I have some work planned that might conflict with these changes, so I would like to know whether to build mine on top of btb's work or on master (which would then cause btb's merge to fail).

**Comment by Matt1360** [comment]
+1 from me, if for nothing other than convenience and maybe a neat factor :)

**Comment by zicodxx** [comment]
To be honest I had to think about this very hard since as I personally never saw the potential of such a console. Which is also why I only added a console-style log feature initially. 

But I have to say the source looks much less complicated than I would have imagined it at first.
If no one else has any objections, by all means, merge it.

**Comment by vLKp** [comment]
As of 147bc4ae0a1aa6c7cf092ae3abd096430e52e310, this fails to merge due to an XCode project file:
```
M  SConstruct
M  common/include/console.h
A  common/main/cli.h
A  common/main/cmd.h
A  common/main/cvar.h
UU contrib/dxx-rebirth.xcodeproj/project.pbxproj
M  similar/arch/sdl/event.cpp
A  similar/main/cli.cpp
A  similar/main/cmd.cpp
M  similar/main/console.cpp
A  similar/main/cvar.cpp
```

I can drop the XCode changes and merge the rest of it, but that may break the Mac build.  I cannot see how to repair the XCode project file.

**Comment by btb** [comment]
should merge cleanly again, and fixed some more warning/errors

**Comment by vLKp** [comment]
I am cleaning up this code prior to merging it.

**Comment by vLKp** [comment]
Is there something missing?  As of b69dee5c07294324cfa34a18ae039720100cc107, there are no uses of [cvar_registervariable](https://github.com/btb/dxx-rebirth/blob/b69dee5c07294324cfa34a18ae039720100cc107/similar/main/cvar.cpp#L125), so [cvar_list](https://github.com/btb/dxx-rebirth/blob/b69dee5c07294324cfa34a18ae039720100cc107/similar/main/cvar.cpp#L30) will always be empty.

**Comment by btb** [comment]
> Is there something missing? As of b69dee5, there are no uses of cvar_registervariable, so cvar_list will always be empty.

Yes, that's correct. This is just to put the framework in place. You'll have to decide later what things you want to expose as cvars. for example, all the config variables, as shown in https://github.com/btb/dxx-rebirth/pull/2

**Pull request merged**
