### PR TITLE
Implement Nonlinear Joystick Settings

### PR DESCRIPTION
**Pull request by Mako88**
Decided to make this a pull request for the time being :)

### CODE REVIEW

**Comment by Mako88** [comment]
Yeah, apparently my editor doesn't like blank lines with tabs in them...

I defined different ones for readability, but if you think it'd be better to reuse DXX_INPUT_SENSITIVITY, I can rewrite it to use that.

I'll also refactor to make a helper function. I'll do that this evening, and re-submit the pull request.

**Comment by Mako88** [comment]
OK, should be all fixed for merging now. I'm unable to test it till this evening, but it SHOULD be fine. I'll test it and get back to you.

**Comment by vLKp** [comment]
I did not mean that you should put the whitespace back.  I meant that it is hard to review the request through the Github web interface (which lacks a `--ignore-all-space` option) when you change whitespace in the same commit where you do real work.  The change looks fine.  I will merge it shortly.

**Comment by vLKp** [comment]
Squashed into a single commit and merged as fe71a94d53d7709e90b9fbf4dfe17b5efd37e872.

**Pull request closed without merging**
